version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
        #- MYSQL_DATABASE=database
        #- MYSQL_USER=user
      - MYSQL_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always
    networks:
      - mysql-phpmyadmin
networks:
  mysql-phpmyadmin:
volumes:
  mysql_data:
